name: CI-TEST
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  ci-test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          k8sVersion: ["1.23.x", "1.24.x", "1.25.x", "1.26.x", "1.27.x", "1.28.x", "1.29.x", "1.30.x"]
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
    - uses: ./.github/actions/install-deps
      with:
        k8sVersion: ${{ matrix.k8sVersion }}
    - run: K8S_VERSION=${{ matrix.k8sVersion }} make ci-test
